### PR TITLE
Fix social icons

### PR DESCRIPTION
**Pull request by Aloso**
I changed social icons in the footer and added tooltips to them. The same modifications have already been accepted at rust-lang/www.rust-lang.org

### CODE REVIEW

**Comment by Aloso** [comment]
I haven't figured out yet how to run the website. Could you explain or point me in the right direction?

**Comment by steveklabnik** [comment]
> I haven't figured out yet how to run the website locally. Could you explain or point me in the right direction?

`cargo run` and then `python -m SimpleHTTPServer` inside the `site` directory.

**Comment by Aloso** [comment]
> Your git information is different than your github account

That's a mistake. I'm not sure if I have to use my username or my name. My IDE (IntelliJ) suggests my username, but I believe git from cmd uses my name by default. The emails should match.

**Comment by Aloso** [comment]
@steveklabnik I just noticed that I used the wrong email address. I hope this is not a problem!

**Comment by steveklabnik** [comment]
Not at all! Thanks a ton :)

**Pull request merged**
