### PR TITLE
Add renovatebot configuration

### PR DESCRIPTION
**Pull request by Turbo87**
This PR adds a basic configuration file for https://docs.renovatebot.com. The configuration was derived from what we are using at https://github.com/rust-lang/crates.io/blob/main/.github/renovate.json5, but significantly simplified.

This should hopefully help us in keeping the dependencies of this project a bit more up-to-date :)

### CODE REVIEW

**Comment by Turbo87** [comment]
@rust-lang/website any thoughts on this? :)

**Comment by CleanCut** [comment]
What about [Dependabot](https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/)? It's built-in to GitHub.

**Comment by Turbo87** [comment]
renovate is a lot more flexible/configurable, feature-rich and open source :)

**Comment by Turbo87** [comment]
@Manishearth ?

**Review by Manishearth — APPROVED** [review]

**Comment by ehuss** [comment]
@Turbo87 Can we put this on a schedule, say once or month or so, to reduce the spam?

**Comment by Turbo87** [comment]
we definitely can. question is whether we should… 😅 

I personally prefer having updates visible as soon as they are available and my email client ignores all GitHub notifications from renovatebot. I'm open to changing it though if the other maintainers of this repo would prefer that. the [dependency dashboard](https://github.com/rust-lang/blog.rust-lang.org/issues/1188) would show the pending updates anyway, with an option to trigger them manually.

**Pull request merged**
