### PR TITLE
Announce Rustup 1.24.0

### PR DESCRIPTION
**Pull request by kinnison**
This is a release announcement for Rustup.

Our expectation is that we can make the release early next week, so I've dated it for Monday currently.

The release is now staged on Rustup's stable branch ready, but we have *NOT* made the release yet.

### CODE REVIEW

**Comment by jonhoo** [comment]
Should https://github.com/rust-lang/rustup/pull/2678 be mentioned in here too?

**Comment by kinnison** [comment]
> Should [rust-lang/rustup#2678](https://github.com/rust-lang/rustup/pull/2678) be mentioned in here too?

My gut feeling was not to, it is in the CHANGELOG but it seemed fairly niche to me.  If you think it deserves greater prominence then I can add something about that.

**Comment by jonhoo** [comment]
No, I'll defer to your judgement here, just wanted to check it wasn't by accident :)

**Comment by pietroalbini** [comment]
The post looks great! I'm wondering if highlighting https://github.com/rust-lang/rustup/pull/2670 would be worth it. I'm not a Windows user, but the change seems like a great UX improvement on that platform.

**Comment by kinnison** [comment]
@pietroalbini Given that change only takes effect on installation, not upgrade, I'm not sure it's worth mentioning in the release announcement since that's (IMO) more for those who already have Rustup installed.

I will fix up the dates on this PR today given we hope to release tomorrow (27th)

**Comment by pietroalbini** [comment]
@kinnison I think it'd still be useful to mention it, even if it only applies to new installations (we should make that explicit).

**Comment by kinnison** [comment]
@pietroalbini How does that read to you?  I'm not sure of the best language to use here but I think that conveys the point.

**Review by pietroalbini — APPROVED** [review]

**Comment by Manishearth** [comment]
Let us know when you need us to merge!

**Comment by pietroalbini** [comment]
I'm going to handle the merge as part of releasing the new rustup version!

**Pull request merged**
