### PR TITLE
Add traits sprint 3 summary

### PR DESCRIPTION
**Pull request by jackh726**
cc @nikomatsakis

### CODE REVIEW

**Comment by XAMPPRocky** [comment]
@jackh726 Does this need further review before publishing? If not I can update the date and merge it.

**Comment by jackh726** [comment]
@XAMPPRocky I don't think so. It's already had a couple eyes on it. So, just the date needs updating.

**Comment by XAMPPRocky** [comment]
@jackh726 Okay, I'll update and publish it tomorrow as the new stable release is today.

**Comment by nikomatsakis** [comment]
Looks good to me, sorry for being slow on feedback.

**Pull request merged**
