### PR TITLE
Rust 1.82.0 announcement post: Fix incorrect listed implementing type for inherent implementation containing newly stabilized std::rc::Rc::assume_init

### PR DESCRIPTION
**Pull request by schuelermine**
it’s not on `Rc<T>`

[Rendered](https://github.com/schuelermine/blog.rust-lang.org/blob/Rust%201.82.0%20announcement%20post%3A%20Fix%20incorrect%20listed%20implementing%20type%20for%20inherent%20implementation%20containing%20newly%20stabilized%20std%3A%3Arc%3A%3ARc%3A%3Aassume_init/posts/2024-10-17-Rust-1.82.0.md)

### CODE REVIEW

**Review by ehuss — APPROVED** [review]
@cuviper Do you concur?

**Comment by cuviper** [comment]
Yes, and `Arc` needs the same fix a few lines down. These should also be fixed in the rust repo's `RELEASES.md`.

**Comment by cuviper** [comment]
Oh, `Box` too!

**Comment by cuviper** [comment]
> These should also be fixed in the rust repo's `RELEASES.md`.

I've submitted this in https://github.com/rust-lang/rust/pull/132040

**Review by ehuss — APPROVED** [review]
Thanks! I went ahead and pushed the change for the other two types.

**Pull request merged**
