### PR TITLE
Add Error Handling Project Group Announcement post

### PR DESCRIPTION
**Pull request by seanchen1991**
This PR adds the announcement post for the Error Handling project group: [https://github.com/rust-lang/rfcs/pull/2965](https://github.com/rust-lang/rfcs/pull/2965). 

Please let me know if there are any formatting/content changes that need to be made to the post before it can go live!

### CODE REVIEW

**Comment by pietroalbini** [comment]
We usually did announcements like this on the Inside Rust blog (`posts/inside-rust`), is there a reason why this is on the main blog?

**Comment by seanchen1991** [comment]
Nope 😂
My bad. I'll open a PR on the Inside Rust blog.

**Comment by pietroalbini** [comment]
@seanchen1991 you don't need to open another PR :)

Just reopen this and move the file to `posts/inside-rust`.

**Comment by seanchen1991** [comment]
This should be ready to merge now 🙂

**Comment by Mark-Simulacrum** [comment]
I think we should hold off until the repository has the readme filled out and such.

**Review by KodrAus — APPROVED** [review]
Sorry for going dark @seanchen1991! This looks good to me

**Comment by seanchen1991** [comment]
@Mark-Simulacrum This should be good to be merged now 🙂

**Comment by Mark-Simulacrum** [comment]
Exciting!

**Pull request merged**
