### PR TITLE
Post about testing Cargo's sparse registry

### PR DESCRIPTION
**Pull request by ehuss**
The Cargo team would like to gather some more feedback on testing the new sparse protocol service.

### CODE REVIEW

**Comment by Eh2406** [comment]
This looks good! Thank you!

**Review by weihanglo — APPROVED** [review]

**Review by arlosi — APPROVED** [review]

**Comment by arlosi** [comment]
Should we include a link on the top of the previous blog post about sparse pointing to this one?
https://github.com/rust-lang/blog.rust-lang.org/blob/master/posts/2022-06-22-sparse-registry-testing.md

**Review by joshtriplett — APPROVED** [review]

**Comment by joshtriplett** [comment]
@ehuss Approved, merge when ready.

**Comment by ehuss** [comment]
> Should we include a link on the top of the previous blog post

Sure, I went ahead and added a link there, thanks!

**Pull request merged**
