### PR TITLE
Spellchecker

### PR DESCRIPTION
**Pull request by alexbowers**

### CODE REVIEW

**Comment by alexbowers** [comment]
Example of this working: https://github.com/alexbowers/rust-spellcheck-test

**Comment by alexbowers** [comment]
Travis showing it failed: https://travis-ci.org/rust-lang/blog.rust-lang.org/builds/270982192

**Comment by alexbowers** [comment]
Well, it was a hard process, but a build showing it working.

https://travis-ci.org/rust-lang/blog.rust-lang.org/builds/271046199

**Comment by steveklabnik** [comment]
Awesome! 

Can you remove that test file now? And then I'm happy to merge.

Thanks so much!

**Comment by alexbowers** [comment]
Completely forgot. Will do when I get home. Then I'll submit a or against all outstanding failures

**Comment by alexbowers** [comment]
@steveklabnik Removed

**Comment by alexbowers** [comment]
ping @steveklabnik

**Comment by steveklabnik** [comment]
Thank you!

**Pull request merged**
