### PR TITLE
[inside-rust]: Update self-profile blog post for measureme 9.0

### PR DESCRIPTION
**Pull request by wesleywiser**
We just released measureme 0.8 which now records trace data into one
file instead of three different ones. I've updated the blog post to
reflect this since many people still use it as a getting started
tutorial.

### CODE REVIEW

**Review by Mark-Simulacrum — COMMENTED** [review]
I think I might rather see us publish a new one with similar/identical contents but add a note to each saying "for version .x" and linking to the newest one.

**Comment by wesleywiser** [comment]
I think I agree in the general case, but the only change here is that the file extensions are different and there is only one file instead of three. IMO having two articles that are so similar would be more confusing than helpful. 

I think it's possible make these edits in such a way that the commands would work for any version of the tools. Would that be better?

**Comment by Mark-Simulacrum** [comment]
Hm. I think we should add a note at least that we've updated the article for a more recent release and point at git history for the old version.

I don't think we should try to make it compatible with both.

**Comment by wesleywiser** [comment]
I've added a note that links to the current version of the post via Github.

**Comment by rylev** [comment]
@wesleywiser we're on measureme 10.0.0 now. Shall we close this?

**Comment by wesleywiser** [comment]
I'd be happy to spend some time updating it for 10.0 if we're fine with the idea of updating the article in general. If we'd rather just leave it as it was originally published, then we should close this.

**Comment by rylev** [comment]
I am personally a fan of creating a new blog entry and only updating the old post to prominently display a link to the new entry. However, I don't hold this opinion super strongly, so just take this as my 2cents.

**Pull request closed without merging**
