### PR TITLE
Switch to GitHub Actions from Travis CI

### PR DESCRIPTION
**Pull request by XAMPPRocky**
r? @pietroalbini

### CODE REVIEW

**Comment by pietroalbini** [comment]
We probably want to setup caching: blog builds need to be as fast as possible, especially during releases.

**Comment by XAMPPRocky** [comment]
@pietroalbini In the future, I plan to experiment with making the blog built through some existing static site generator or mdbook. This will provide the biggest CI speed bump as we can download/cache a prebuilt binary. If you have a good caching method for github actions I can add it.

**Comment by pietroalbini** [comment]
@XAMPPRocky the crates.io repo [has an example of that](https://github.com/rust-lang/crates.io/blob/fb925f92981dd30192c460d3897d07008fc94621/.github/workflows/ci.yml#L146-L157).

**Comment by XAMPPRocky** [comment]
@pietroalbini I've added the cache, so this should be ready to merge.

**Comment by pietroalbini** [comment]
This looks great! Thanks @XAMPPRocky for writing this!

We can merge this on Friday: I want to still have the known good CI for release day.

**Comment by nikomatsakis** [comment]
It's Friday, so merging!

**Pull request merged**
