### PR TITLE
Announce std::simd is on nightly

### PR DESCRIPTION
**Pull request by workingjubilee**
Not 100% sure if this should go on the main blog or Inside Rust.

### CODE REVIEW

**Comment by rylev** [comment]
@workingjubilee sorry for letting this sit for so long. Would it still make sense for this to be updated and released or is it too late, and this should be closed?

**Comment by programmerjake** [comment]
imho this is still useful, though it may need to be updated to the latest portable-simd API.

**Comment by Turbo87** [comment]
it's been over two years, if this is actually still relevant then it's probably best to open a new PR with an updated text 😉

**Comment by workingjubilee** [comment]
@Turbo87 What are you winking at? Our discords?

And 3, actually.

Having to answer "this should be closed" for a reason that is no fault of my own is demoralizing, which is half of why I simply did not. The other half is the lack of reason to believe that I would not get a response, if I opened something now, sooner than 2025, unless I did something to further piss everyone off.

**Comment by Turbo87** [comment]
I was just assuming that the content is probably not up-to-date anymore and since there hasn't been any movement for a long while I closed it, but feel free to reopen if you still want to land it :)

**Pull request closed without merging**
