### PR TITLE
Inside Rust: February CTCFT agenda

### PR DESCRIPTION
**Pull request by AngelOnFira**
This adds the agenda for the February CTCFT meeting.

### CODE REVIEW

**Comment by badboy** [comment]
Should this go on the [Inside Rust](https://blog.rust-lang.org/inside-rust/index.html) blog instead?

**Comment by AngelOnFira** [comment]
@badboy yes, thanks for pointing that out :) I think the file should be in the right place now :+1:

**Comment by AngelOnFira** [comment]
Great, thanks!

**Comment by AngelOnFira** [comment]
Sorry, actually one more thing

**Review by badboy — APPROVED** [review]

**Pull request merged**
