### PR TITLE
Announce major Generator -> Coroutine rename

### PR DESCRIPTION
**Pull request by oli-obk**
cc https://github.com/rust-lang/rust/pull/116447
cc https://github.com/rust-lang/rust/pull/116958

### CODE REVIEW

**Review by Mark-Simulacrum — APPROVED** [review]
Seems ok!

**Comment by the8472** [comment]
Probably should mention that it's only relevant for nightly users.

**Comment by oli-obk** [comment]
Updated. what do I need to do to publish this?

**Review by Mark-Simulacrum — APPROVED** [review]

**Comment by Mark-Simulacrum** [comment]
Currently date is set for tomorrow, I can merge then (ping me). Or happy to publish today, but then date should be updated.

**Review by Mark-Simulacrum — APPROVED** [review]

**Comment by jeffparsons** [comment]
> huh... I... should probably not be writing blog posts at 2am... not sure why I used the 24th.

No, you definitely should, because this was super entertaining reading. Can you write all the Rust blog posts from now on? 😛

One question, though: you mentioned that generators are a convenient way to write iterators. Isn't there also a performance angle? For some reason I had the impression that the compiler-generated state machine would be faster than what, e.g., `chain` can do today. Is that actually true, or did I make that up?

**Comment by oli-obk** [comment]
For a very simple `chain` I would think that it comes out as equivalent. We'll have to actually look at examples and codegen to see where we can improve things. In the end, we'll try to be zero cost where plausible

**Pull request merged**
