### PR TITLE
Make the blogs highlight style inline with the website

### PR DESCRIPTION
**Pull request by XAMPPRocky**
Companion PR to https://github.com/rust-lang/www.rust-lang.org/pull/1165

### Production

Screenshot 2020-07-01 at 10 17 27

### Proposed

Screenshot 2020-07-01 at 10 17 15

### CODE REVIEW

**Comment by lzutao** [comment]
Does the change on phone still produce the same ouptput?

**Comment by XAMPPRocky** [comment]
Screenshot 2020-07-01 at 10 55 47

**Comment by nikomatsakis** [comment]
I don't think I'm a good assignee here!

r? @Manishearth perhaps?

**Comment by Manishearth** [comment]
As I mentioned in https://github.com/rust-lang/www.rust-lang.org/pull/1165 , I believe the highlight style chosen here was a deliberate choice. I've seen this kind of styling before across the web.

**Comment by skade** [comment]
Given that there's positive review on the website topic (https://github.com/rust-lang/www.rust-lang.org/pull/1165#issuecomment-653898386), I assume this one is good, too.

**Comment by XAMPPRocky** [comment]
Yep, but this shouldn’t be merged yet, the www PR needs to merge and then the website needs to be deployed so that the change happens simultaneously. I also have to make a PR to thanks.

**Pull request merged**
