### PR TITLE
[Inside-Rust] Welcome David Wood to compiler team & Jack Huey to contributors

### PR DESCRIPTION
**Pull request by wesleywiser**
Congrats @davidtwco and @jackh726! 🎉 

r? @pnkfelix

### CODE REVIEW

**Comment by pnkfelix** [comment]
r+

**Comment by jyn514** [comment]
@pnkfelix bors isn't enabled in this repo, you have to merge by hand :P

**Comment by pnkfelix** [comment]
@jyn514 I don't have permissions to do so (I'm not part of core). I'm just trying to signal that I'm signing off on this change.

**Comment by wesleywiser** [comment]
Updated the post for today's date. This is ready to merge.

**Pull request merged**
