### PR TITLE
Improve design of footer links

### PR DESCRIPTION
**Pull request by Aloso**
Issue: [#610 on www.rust-lang.org](https://github.com/rust-lang/www.rust-lang.org/issues/610)

### CODE REVIEW

**Comment by steveklabnik** [comment]
Could you rebase this, please? Then we can merge :)

**Comment by steveklabnik** [comment]
sorry, i'm still seeing the merge commits in there.

if you can't get them out, I can take a crack at it :)

**Comment by Aloso** [comment]
> if you can't get them out, I can take a crack at it :)

Please do. I'm sorry, I'm still new to using git as a contributor.

**Comment by steveklabnik** [comment]
No worries! Applied in https://github.com/rust-lang/blog.rust-lang.org/commit/ad3392c0cf528e49680d3ba6cfdb279c5f3cb53f

Usually what I do in this case is something like

```console
> git fetch https://github.com/rust-lang/blog.rust-lang.org
> git rebase FETCH_HEAD
> git push origin -f
```

Sometimes, you end up fighting with rebase... anyway, glad we got this in, and thank you!

**Pull request closed without merging**
