### PR TITLE
Add CC-BY 4.0 as LICENSE

### PR DESCRIPTION
**Pull request by skade**
This adds the CC-BY license as license to this repository, as discussed in #63, and https://github.com/rust-lang/rust/issues/25664#issuecomment-240557740.

This requires sign-off by all contributors. I'll assemble a list.

### CODE REVIEW

**Comment by skade** [comment]
Considering our contribution pattern and the nature of the work here, I'd argue that we don't need sign-off from everyone: https://github.com/rust-lang/blog.rust-lang.org/graphs/contributors

My proposal would be to just ask people with more then 10 lines of additions. All others only contributed minor typo fixes, while the work is clearly the work of the other authors.

@aturon, would that be fine?

**Comment by aturon** [comment]
SGTM

**Comment by skade** [comment]
Hi everyone,

we'd finally like to put a license the contents of the Rust language blog, and would propose using the CC-BY license (Attribution).

* [ ] @steveklabnik
* [ ] @aturon
* [ ] @pnkfelix
* [ ] @brson
* [ ] @carols10cents
* [ ] @alexcrichton
* [ ] @nikomatsakis
* [ ] @alexbowers
* [ ] @jonathandturner
* [ ] @huonw
* [ ] @erickt
* [ ] @GuillaumeGomez

Would you please reply in this thread if you are good with it, I'll then check you off.

Florian

**Comment by alexbowers** [comment]
Im fine with it.

**Comment by GuillaumeGomez** [comment]
Fine for me as well.

**Comment by jonathandturner** [comment]
I approve

**Comment by steveklabnik** [comment]
I've checked it off, but I approve.

**Comment by nikomatsakis** [comment]
I approve.

**Comment by skade** [comment]
@pnkfelix sent me his agreement via IRC.

**Comment by skade** [comment]
@aturon can you - as project lead - speak for @huonw or @brson (which, to my knowledge, made the substantial parts of their contributions as Mozilla employees?)

**Comment by skade** [comment]
@aturon Ping. I would really like to close this before the end of the year.

**Comment by steveklabnik** [comment]
Everyone at Mozilla is on vacation now, until the second.

**Comment by skade** [comment]
@aturon Ping again. I'll  myself from this issue on Jan, 5th if it doesn't move forward.

**Comment by skade** [comment]
@ashleygwilliams Just noticed that through publishing a full blog post, you became a substantial author and need to sign this off as well.

**Comment by ashleygwilliams** [comment]
i approve and checked the box by my name. thanks for the diligence on this @skade !

**Comment by aturon** [comment]
I'm willing to speak for @huonw and @brson, yes. Let's merge this!

**Pull request merged**
