### PR TITLE
Project goals RFC approved

### PR DESCRIPTION
**Pull request by nikomatsakis**
Brief update

### CODE REVIEW

**Comment by jackh726** [comment]
Do you think it's worth having both an inside Rust blog post and a main blog Post?

**Comment by nikomatsakis** [comment]
> Do you think it's worth having both an inside Rust blog post and a main blog Post?

I figured it can't hurt, blog posts are free... but I'm ok with deferring. I need to write the main blog post this week.

**Comment by jackh726** [comment]
No strong concern...just in some sense trying to avoid "update fatigue" - better imo to have one really strong update than a couple less-complete updates in a short period.

That being said, happy to merge this if you want and change the date!

**Comment by nikomatsakis** [comment]
Meh, at this point it doesn't make sense. Closing in favor of #1374.

**Pull request closed without merging**
