### PR TITLE
Async Rust in 2022

### PR DESCRIPTION
**Pull request by tmandry**
Note that this depends on landing https://github.com/rust-lang/team/pull/698.

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
cc/ @rust-lang/wg-async as well

**Review by yoshuawuyts — APPROVED** [review]
This looks good!

**Review by rylev — CHANGES_REQUESTED** [review]
Looks good! The date of the post needs to be changed though!

**Review by rylev — APPROVED** [review]
🎉

**Pull request merged**
