### PR TITLE
Break promise

### PR DESCRIPTION
**Pull request by m-ou-se**
This quietly removes a promise we didn't fulfill. (:

cc @rust-lang/project-edition-2021

### CODE REVIEW

**Review by Manishearth — APPROVED** [review]
"oops"

**Comment by steveklabnik** [comment]
I am not really sure that hiding this is a good thing. Sometimes we don't follow through on things, but just deleting it feels *real* bad to me.

**Comment by Manishearth** [comment]
@m-ou-se perhaps we should restore the line and add an italicized "note: we didn't end up doing this" or something?

**Comment by Manishearth** [comment]
https://github.com/rust-lang/blog.rust-lang.org/pull/859

**Pull request merged**
